export type ServiceCategory = 'women' | 'men'

export interface ServiceData {
  slug: string
  name: string
  category: ServiceCategory
  price: number
  priceDisplay: string
  group: string
  groupName: string
  description: string
  sessions: string
}

export const servicesData: ServiceData[] = [
  // Women's services
  {
    slug: 'upper-lip',
    name: 'Upper Lip',
    category: 'women',
    price: 85,
    priceDisplay: 'R85',
    group: 'face',
    groupName: 'Face & Neck',
    description: 'Say goodbye to upper lip hair, waxing irritation, and daily upkeep with fast, precise laser treatment.',
    sessions: '4-6 sessions',
  },
  {
    slug: 'brow',
    name: 'Brow',
    category: 'women',
    price: 85,
    priceDisplay: 'R85',
    group: 'face',
    groupName: 'Face & Neck',
    description: 'Clean up stray brow hairs permanently, with precise shaping that keeps your natural brow line intact.',
    sessions: '4-6 sessions',
  },
  {
    slug: 'chin',
    name: 'Chin',
    category: 'women',
    price: 95,
    priceDisplay: 'R95',
    group: 'face',
    groupName: 'Face & Neck',
    description: 'A quick, pain-free treatment for chin hair that leaves skin smooth without the irritation of plucking or waxing.',
    sessions: '4-6 sessions',
  },
  {
    slug: 'top-of-bikini',
    name: 'Top of Bikini',
    category: 'women',
    price: 100,
    priceDisplay: 'R100',
    group: 'bikini',
    groupName: 'Bikini Area',
    description: 'A discreet, professional treatment for the bikini line, ideal for anyone wanting a low-maintenance tidy-up.',
    sessions: '4-6 sessions',
  },
  {
    slug: 'stomach',
    name: 'Stomach',
    category: 'women',
    price: 200,
    priceDisplay: 'R200',
    group: 'body',
    groupName: 'Body',
    description: 'Smooth, hair-free stomach skin with a comfortable treatment suited to sensitive skin.',
    sessions: '4-6 sessions',
  },
  {
    slug: 'bikini-sides',
    name: 'Bikini Sides',
    category: 'women',
    price: 110,
    priceDisplay: 'R110',
    group: 'bikini',
    groupName: 'Bikini Area',
    description: 'Targeted treatment for the bikini sides, giving clean, confident lines all year round.',
    sessions: '4-6 sessions',
  },
  {
    slug: 'full-hollywood',
    name: 'Full Hollywood',
    category: 'women',
    price: 350,
    priceDisplay: 'R350',
    group: 'bikini',
    groupName: 'Bikini Area',
    description: 'Complete bikini area treatment, carried out discreetly and professionally for total smoothness.',
    sessions: '4-6 sessions',
  },
  {
    slug: 'underarms',
    name: 'Underarms',
    category: 'women',
    price: 120,
    priceDisplay: 'R120',
    group: 'underarms',
    groupName: 'Underarms',
    description: 'One of our quickest treatments — say goodbye to daily shaving and razor burn for good.',
    sessions: '4-6 sessions',
  },
  {
    slug: 'full-face',
    name: 'Full Face',
    category: 'women',
    price: 395,
    priceDisplay: 'R395',
    group: 'face',
    groupName: 'Face & Neck',
    description: 'A complete facial treatment covering lip, chin, and cheeks for an all-over flawless finish.',
    sessions: '4-6 sessions',
  },
  {
    slug: 'half-arms',
    name: 'Half Arms',
    category: 'women',
    price: 200,
    priceDisplay: 'R200',
    group: 'arms',
    groupName: 'Arms',
    description: 'Smooth, hair-free arms from elbow to wrist, perfect for short sleeves with confidence.',
    sessions: '4-6 sessions',
  },
  {
    slug: 'half-legs',
    name: 'Half Legs',
    category: 'women',
    price: 500,
    priceDisplay: 'R500',
    group: 'legs',
    groupName: 'Legs',
    description: 'Silky smooth lower legs without the hassle of regular shaving or waxing appointments.',
    sessions: '4-6 sessions',
  },
  {
    slug: 'full-legs',
    name: 'Full Legs',
    category: 'women',
    price: 700,
    priceDisplay: 'R700',
    group: 'legs',
    groupName: 'Legs',
    description: 'Long-lasting smoothness from thigh to ankle, with fewer sessions needed thanks to our 4-wavelength machine.',
    sessions: '4-6 sessions',
  },
  {
    slug: 'full-body',
    name: 'Full Body',
    category: 'women',
    price: 1000,
    priceDisplay: 'R1,000',
    group: 'full-body',
    groupName: 'Full Body',
    description: 'Our most comprehensive treatment — complete head-to-toe smoothness in one convenient session.',
    sessions: '4-6 sessions',
  },
  // Men's services
  {
    slug: 'ear-hair',
    name: 'Ear Hair',
    category: 'men',
    price: 120,
    priceDisplay: 'R120',
    group: 'face',
    groupName: "Men's Face",
    description: 'A quick, precise treatment to keep ear hair permanently under control.',
    sessions: '4-6 sessions',
  },
  {
    slug: 'nose-hair',
    name: 'Nose Hair',
    category: 'men',
    price: 150,
    priceDisplay: 'R150',
    group: 'face',
    groupName: "Men's Face",
    description: 'Fast, comfortable treatment for nose hair, done with precision and care.',
    sessions: '4-6 sessions',
  },
  {
    slug: 'mens-underarms',
    name: 'Underarms',
    category: 'men',
    price: 195,
    priceDisplay: 'From R195',
    group: 'underarms',
    groupName: "Men's Underarms",
    description: 'A quick, effective treatment for men that eliminates the need for daily shaving.',
    sessions: '4-6 sessions',
  },
  {
    slug: 'half-leg',
    name: 'Half Leg',
    category: 'men',
    price: 400,
    priceDisplay: 'R400',
    group: 'legs',
    groupName: "Men's Legs",
    description: 'Smooth, hair-free lower legs with lasting results from our advanced laser technology.',
    sessions: '4-6 sessions',
  },
  {
    slug: 'half-arm',
    name: 'Half Arm',
    category: 'men',
    price: 450,
    priceDisplay: 'R450',
    group: 'arms',
    groupName: "Men's Arms",
    description: 'A comfortable, effective treatment for smooth forearms without the upkeep of shaving.',
    sessions: '4-6 sessions',
  },
  {
    slug: 'mens-stomach',
    name: 'Stomach',
    category: 'men',
    price: 595,
    priceDisplay: 'From R595',
    group: 'body',
    groupName: "Men's Body",
    description: 'Professional stomach hair removal with a comfortable, pain-free experience.',
    sessions: '4-6 sessions',
  },
  {
    slug: 'back',
    name: 'Back',
    category: 'men',
    price: 595,
    priceDisplay: 'From R595',
    group: 'body',
    groupName: "Men's Body",
    description: 'One of our most popular men\'s treatments — permanent, professional back hair removal.',
    sessions: '4-6 sessions',
  },
  {
    slug: 'beard-and-neck',
    name: 'Beard and Neck',
    category: 'men',
    price: 600,
    priceDisplay: 'R600',
    group: 'face',
    groupName: "Men's Face",
    description: 'Precision shaping and permanent reduction for beard line and neck hair.',
    sessions: '4-6 sessions',
  },
  {
    slug: 'mens-arms',
    name: 'Arms',
    category: 'men',
    price: 700,
    priceDisplay: 'R700',
    group: 'arms',
    groupName: "Men's Arms",
    description: 'Full arm treatment for men wanting lasting smoothness without regular shaving.',
    sessions: '4-6 sessions',
  },
  {
    slug: 'mens-legs',
    name: 'Legs',
    category: 'men',
    price: 800,
    priceDisplay: 'R800',
    group: 'legs',
    groupName: "Men's Legs",
    description: 'Complete leg treatment for men, delivering long-lasting results in fewer sessions.',
    sessions: '4-6 sessions',
  },
]

export function getServiceBySlug(slug: string): ServiceData | undefined {
  return servicesData.find((s) => s.slug === slug)
}

export function getRelatedServices(service: ServiceData, count = 3): ServiceData[] {
  return servicesData
    .filter((s) => s.slug !== service.slug && s.group === service.group)
    .slice(0, count)
}
